/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import java.sql.SQLException;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author asust
 * Nadia Azura Nurhaniya- 24060124120019
 */
public class JFrameUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());
    private final MysqlMahasiswaService service;
    /**
     * Creates new form JFrameUtama
     * @throws java.sql.SQLException
     */
    public JFrameUtama() throws SQLException {
        initComponents();
        service = new MysqlMahasiswaService();
        tampilData();
    }

    private void tampilData() throws SQLException {
        DefaultListModel<String> modelId = new DefaultListModel<>();
        DefaultListModel<String> modelNama = new DefaultListModel<>();

        List<Mahasiswa> data = service.getAll();

        for (Mahasiswa mhs : data) {
            modelId.addElement(String.valueOf(mhs.getId()));
            modelNama.addElement(mhs.getNama());
        }

        listId.setModel(modelId);
        listNama.setModel(modelNama);
    }
    
    private void bersihkanForm() {
        txtNama.setText("");
        txtIdEdit.setText("");
        txtNamaEdit.setText("");
        txtIdHapus.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAmbilSemua = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnTambahkan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listId = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listNama = new javax.swing.JList<>();
        btnEdit = new javax.swing.JToggleButton();
        btnHapus = new javax.swing.JToggleButton();
        btnResetIndeks = new javax.swing.JToggleButton();
        txtIdEdit = new javax.swing.JTextField();
        txtNamaEdit = new javax.swing.JTextField();
        txtIdHapus = new javax.swing.JTextField();
        txtNamaHapus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("NAMA");

        jLabel3.setText("Kelola Data Mahasiswa");

        btnAmbilSemua.setText("Ambil Semua Data");
        btnAmbilSemua.addActionListener(this::btnAmbilSemuaActionPerformed);

        jLabel4.setText("Nama:");

        txtNama.addActionListener(this::txtNamaActionPerformed);

        btnTambahkan.setText("Tambahkan");
        btnTambahkan.addActionListener(this::btnTambahkanActionPerformed);

        listId.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listIdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listId);

        listNama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNamaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listNama);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnResetIndeks.setText("Reset Indeks");
        btnResetIndeks.addActionListener(this::btnResetIndeksActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaEdit)
                                    .addComponent(txtNamaHapus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnTambahkan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnResetIndeks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnAmbilSemua)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 16, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAmbilSemua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnEdit)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnHapus)
                                    .addComponent(txtIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 66, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnTambahkan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnResetIndeks))))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAmbilSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbilSemuaActionPerformed
        try {
            // TODO add your handling code here:
            tampilData();
        } catch (SQLException ex) {
            System.getLogger(JFrameUtama.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnAmbilSemuaActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnTambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahkanActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong");
            return;
        }

        Mahasiswa mhs = new Mahasiswa(nama);
        try {
            service.add(mhs);
        } catch (SQLException ex) {
            System.getLogger(JFrameUtama.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        bersihkanForm();
        try {
            tampilData();
        } catch (SQLException ex) {
            System.getLogger(JFrameUtama.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnTambahkanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtIdEdit.getText());
            String nama = txtNamaEdit.getText();

            if (nama.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong");
                return;
            }

            Mahasiswa mhs = new Mahasiswa(id, nama);
            service.update(mhs);

            bersihkanForm();
            tampilData();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka");
        } catch (SQLException ex) {
            System.getLogger(JFrameUtama.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtNamaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaEditActionPerformed

    private void txtIdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdHapusActionPerformed

    private void txtIdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEditActionPerformed
    
    private void btnResetIndeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetIndeksActionPerformed
        // TODO add your handling code here:
        service.indexReset();
        try {
            tampilData();
        } catch (SQLException ex) {
            System.getLogger(JFrameUtama.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnResetIndeksActionPerformed

    private void listNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNamaMouseClicked
        // TODO add your handling code here:
        int index = listNama.getSelectedIndex();

        if (index >= 0) {
            String id = listId.getModel().getElementAt(index);
            String nama = listNama.getModel().getElementAt(index);

            txtIdEdit.setText(id);
            txtNamaEdit.setText(nama);
            txtIdHapus.setText(id);
        }
    }//GEN-LAST:event_listNamaMouseClicked
    
    private void listIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listIdMouseClicked
        // TODO add your handling code here:
        int index = listId.getSelectedIndex();

        if (index >= 0) {
            String id = listId.getModel().getElementAt(index);
            String nama = listNama.getModel().getElementAt(index);

            txtIdEdit.setText(id);
            txtNamaEdit.setText(nama);
            txtIdHapus.setText(id);
        }
    }//GEN-LAST:event_listIdMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtIdHapus.getText());

            service.delete(id);

            bersihkanForm();
            tampilData();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka");
        } catch (SQLException ex) {
            System.getLogger(JFrameUtama.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new JFrameUtama().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(JFrameUtama.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbilSemua;
    private javax.swing.JToggleButton btnEdit;
    private javax.swing.JToggleButton btnHapus;
    private javax.swing.JToggleButton btnResetIndeks;
    private javax.swing.JButton btnTambahkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listId;
    private javax.swing.JList<String> listNama;
    private javax.swing.JTextField txtIdEdit;
    private javax.swing.JTextField txtIdHapus;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaEdit;
    private javax.swing.JTextField txtNamaHapus;
    // End of variables declaration//GEN-END:variables
}
